<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>MarkupServer</AssemblyTitle>
    <Product>MarkupServer</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Analyzer Include="..\packages\Microsoft.VisualStudio.Threading.Analyzers.17.6.40\analyzers\cs\Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.dll" />
    <Analyzer Include="..\packages\Microsoft.VisualStudio.Threading.Analyzers.17.6.40\analyzers\cs\Microsoft.VisualStudio.Threading.Analyzers.CSharp.dll" />
    <Analyzer Include="..\packages\Microsoft.VisualStudio.Threading.Analyzers.17.6.40\analyzers\cs\Microsoft.VisualStudio.Threading.Analyzers.dll" />
    <Analyzer Include="..\packages\Microsoft.VisualStudio.Threading.Analyzers.17.6.40\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.dll" />
    <Analyzer Include="..\packages\Microsoft.VisualStudio.Threading.Analyzers.17.6.40\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.dll" />
    <Analyzer Include="..\packages\Microsoft.VisualStudio.Threading.Analyzers.17.6.40\analyzers\vb\Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll" />
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.7.2" />
    <PackageReference Include="MessagePack" Version="2.5.108" />
    <PackageReference Include="MessagePack.Annotations" Version="2.5.108" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.14.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.NET.StringTools" Version="17.4.0" />
    <PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.6.40" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.6.40" />
    <PackageReference Include="Microsoft.VisualStudio.Validation" Version="17.6.11" />
    <PackageReference Include="Nerdbank.Streams" Version="2.10.66" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="StreamJsonRpc" Version="2.16.36" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
    <PackageReference Include="System.IO.Pipelines" Version="9.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
    <PackageReference Include="System.Threading.Tasks.Dataflow" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Land.Core8">
      <HintPath>lib\Land.Core8.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>